version: '3.6'
services:
  web:
    build: .
    volumes:
      - .:/home/react_rails_docker
    ports:
      - "3000:3000"
    command: rails server -p 3000 -b '0.0.0.0'
    depends_on:
     - db
  webpacker:
    build: .
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    command: ./bin/webpack-dev-server
    volumes:
      - .:/home/react_rails_docker
    ports:
      - '3035:3035'
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: dev_user
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: